### ISSUE TITLE
Deploy source gives RoleArn error

### ISSUE THREAD

**Issue by fedavis-1006** [aws-samples/aws-centralize-logs-using-cdk#2]
When attempting to deploy the LogSourceStack, I get the following error:

```
3:23:25 PM | CREATE_FAILED        | 
AWS::Logs::SubscriptionFilter 
SubscriptionFilter
destinationArn for vendor cloudformation cannot be used without roleArn (Service: AWSLogs; Status Code: 400; 
Error Code:InvalidParameterException; Request ID: db0...
```

This error repeats 4 times.
We created all role types and principal types in an attempt to work around this.
When running as a role we get a different error:
```
3:16:17 PM | CREATE_FAILED        
WS::Logs::SubscriptionFilter 
SubscriptionFilter
PutSubscriptionFilter operation cannot work with destinationArn for vendor cloudformation 
(Service: AWSLogs; Status Code: 400; Error Code: InvalidParameterException; 
Request ID: ...

```
Ideas?

The documentation suggest that the cross account destinations only work with Kinesis, so I am confused how this is supposed to work.

Thanks

**Comment by navbalaraman** [comment]
I tested this again today against 2 separate accounts and it works. If your deployments are similar to below it should happen successfully.

Let's say "account-a" generates the log and needs to be pushed to "account-b"
1. The below command executed against "account-b" gives permission to "account-a" to put a subscription against the logdestination resource. This needs to be executed first.
cdk deploy LogDestinationStack --parameters LogDestinationStack:SourceAccountNumber="account-a" --profile <<Account-B-PROFILE>> --region <<REGION>>

2. Once #1 is completed then the below command is executed against "account-a".
cdk deploy LogSourceStack --parameters LogSourceStack:LogGroupName="<<Log-Group-Name>>" --parameters LogDestinationArn="arn:aws:logs:us-east-2:078876706719:destination:Central-Log-Destination" --profile <<Account-A-PROFILE>> --region <<REGION>>

**Comment by fedavis-1006** [comment]
I restarted from the initial attempt and was able to get it to operate.   I think my associated profile for the source account was misconfigured, picking up the incorrect region.   Thanks.
